apiVersion: v1
kind: Service
metadata:
  name: players-v1-service
  labels:
    app: players-v1-service
spec:
  type: ClusterIP
  selector:
    app: players-v1
  ports:
    - port: 8080     # 8000 flask 8080 fastapi
      targetPort: 8080     # 8000 flask 8080 fastapi
      name: http
      protocol: TCP
  
