version: "3.8"
services:
  database:
    container_name: database
    build:
      context: ./image
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: database-vol
        target: /var/lib/postgresql/data 
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 4s

volumes:
  database-vol: 
    name: database-vol