apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ExternalName
  externalName: database
# ---
# apiVersion: discovery.k8s.io/v1
# kind: EndpointSlice
# metadata:
#   name: database-endpoint-slice
#   labels:
#     kubernetes.io/service-name: database-service
# addressType: IPv4
# ports:
#   - name: '' 
#     protocol: TCP
#     port: 5432
# endpoints:
#   - addresses:
#       - "172.23.0.1"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: database-service
# spec:
#   ports:
#     - protocol: TCP
#       port: 5432
#       targetPort: 5432