apiVersion: v1
kind: Service
metadata:
  name: movies-v1-backend-service
  labels:
    app: movies-v1-backend-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    app: movies-v1-backend
