apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASS: password
  POSTGRES_DB: players
  POSTGRES_HOST: database-service  #TODO check aca
  POSTGRES_PORT: "5432"